package Process;

import Users.*;
import Log.Login;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 91979
 */
public class InsertProduct extends javax.swing.JFrame {
    private Connection con;
    private static PreparedStatement pst;
    private static ResultSet rs;
    private String name;
    private String userType;
    private int id;
    /**
     * Creates new form Admin
     */
    public InsertProduct() {
        initComponents();
        this.con = Login.connection();
        }
    
    public InsertProduct(String name, int id,String userType,Connection con) {
       initComponents();
       jUserId.setText(String.valueOf(id));
       jUserName.setText(name);
       this.con= con;
       this.name = name;
       this.userType = userType;
       this.id=id;
       autoId();
       }
   private  void autoId(){
       String sql = "select Max(tracking_id) max from RequestGRN ";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            boolean check = rs.next();
            if(check){
                int id = Integer.parseInt(rs.getString("max"));
                ++id;
                jTrackId.setText(String.valueOf(id));
            }else{
               jTrackId.setText("1");
            }
        } catch (SQLException ex) {
            Logger.getLogger(InsertProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jUserId = new javax.swing.JLabel();
        jUserName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtProductId = new javax.swing.JTextField();
        jtxtDescription = new javax.swing.JTextField();
        jbtnClear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtxtCostprice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtRetailPrice = new javax.swing.JTextField();
        jtxtQty = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTrackId = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtxtVehicleNo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtxtQuality = new javax.swing.JLabel();
        jbtnInsert = new javax.swing.JButton();
        jtxtProductName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Vendor Product Request Page");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("User Id");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Name");

        jUserId.setBackground(new java.awt.Color(255, 204, 204));
        jUserId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jUserId.setForeground(new java.awt.Color(153, 153, 255));
        jUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUserId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jUserId.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jUserName.setBackground(new java.awt.Color(255, 204, 204));
        jUserName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jUserName.setForeground(new java.awt.Color(153, 153, 255));
        jUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUserName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jUserName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setText("Description");

        jButton6.setBackground(new java.awt.Color(153, 204, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 255));
        jLabel13.setText("Product Id");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 255));
        jLabel14.setText("Product Name");

        jtxtProductId.setBackground(new java.awt.Color(102, 255, 204));
        jtxtProductId.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtProductId.setForeground(new java.awt.Color(0, 0, 255));

        jtxtDescription.setBackground(new java.awt.Color(102, 255, 204));
        jtxtDescription.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtDescription.setForeground(new java.awt.Color(0, 0, 255));
        jtxtDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtDescriptionFocusLost(evt);
            }
        });

        jbtnClear.setBackground(new java.awt.Color(153, 204, 255));
        jbtnClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnClear.setForeground(new java.awt.Color(0, 0, 255));
        jbtnClear.setText("Clear");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 255));
        jLabel11.setText("Costprice");

        jtxtCostprice.setBackground(new java.awt.Color(102, 255, 204));
        jtxtCostprice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtCostprice.setForeground(new java.awt.Color(0, 0, 255));
        jtxtCostprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCostpriceFocusLost(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 255));
        jLabel12.setText("RetailPrice");

        jtxtRetailPrice.setBackground(new java.awt.Color(102, 255, 204));
        jtxtRetailPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtRetailPrice.setForeground(new java.awt.Color(0, 0, 255));
        jtxtRetailPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtRetailPriceFocusLost(evt);
            }
        });

        jtxtQty.setBackground(new java.awt.Color(102, 255, 204));
        jtxtQty.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtQty.setForeground(new java.awt.Color(0, 0, 255));
        jtxtQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtQtyFocusLost(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 255));
        jLabel15.setText("Qty");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 255));
        jLabel16.setText("Tracking Id");

        jTrackId.setBackground(new java.awt.Color(102, 255, 204));
        jTrackId.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTrackId.setForeground(new java.awt.Color(0, 0, 255));
        jTrackId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTrackId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 255));
        jLabel17.setText("Quality");

        jtxtVehicleNo.setBackground(new java.awt.Color(102, 255, 204));
        jtxtVehicleNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtVehicleNo.setForeground(new java.awt.Color(0, 0, 255));
        jtxtVehicleNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtVehicleNoFocusLost(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 255));
        jLabel18.setText("vehicleno");

        jtxtQuality.setBackground(new java.awt.Color(102, 255, 204));
        jtxtQuality.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtQuality.setForeground(new java.awt.Color(0, 0, 255));
        jtxtQuality.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtxtQuality.setText("HOLD");
        jtxtQuality.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtnInsert.setBackground(new java.awt.Color(153, 204, 255));
        jbtnInsert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnInsert.setForeground(new java.awt.Color(0, 0, 255));
        jbtnInsert.setText("Insert");
        jbtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInsertActionPerformed(evt);
            }
        });

        jtxtProductName.setBackground(new java.awt.Color(102, 255, 204));
        jtxtProductName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtProductName.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(0, 191, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(63, 63, 63))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel12))
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTrackId, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtProductName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtRetailPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jtxtDescription, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtCostprice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtQty, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtQuality, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtVehicleNo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap())))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jbtnInsert)
                .addGap(56, 56, 56)
                .addComponent(jbtnClear)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jTrackId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jtxtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jtxtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtCostprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtRetailPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtxtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtxtQuality, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jtxtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnInsert)
                    .addComponent(jbtnClear))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.gc();
        this.setVisible(false);
        new Vendor(name,id,userType,con).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
                autoId();
                jtxtProductId.setText("");
                jtxtProductName.setText("");
                jtxtDescription.setText("");
                jtxtCostprice.setText("");
                jtxtRetailPrice.setText("");
                jtxtQty.setText("");
                jtxtVehicleNo.setText("");
                jtxtProductId.requestFocus();
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jtxtDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtDescriptionFocusLost
//        String utype = jtxtDescription.getText();
//        if(utype.equals("Admin")||
//            utype.equals("Receving")||
//            utype.equals("Quality")||
//            utype.equals("Vendor")||
//            utype.equals("Billing")){
//            jtxtDescription.setText(utype);
//        }else{
//            jtxtDescription.setText("");
//            JOptionPane.showMessageDialog(this, "please enter given details only"
//                + "\n Admin"
//                + "\n Receving"
//                + "\n Quality"
//                + "\n Vendor"
//                + "\n Billing");
//            jtxtDescription.requestFocus();
//        }
    }//GEN-LAST:event_jtxtDescriptionFocusLost

    private void jtxtCostpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCostpriceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostpriceFocusLost

    private void jtxtRetailPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtRetailPriceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRetailPriceFocusLost

    private void jtxtQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtQtyFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQtyFocusLost

    private void jtxtVehicleNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtVehicleNoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVehicleNoFocusLost
    private boolean numcheck(JTextField s){
        boolean flag =false;
        String str = s.getText();
        for(int i=0;i<str.length();i++){
            if('0'<=str.charAt(i)&&str.charAt(i)<='9'){
                flag=true;
            }else{
                flag=false;
                break;
            }
        }
      return flag;  
    }
    private boolean allNumCheck(){
        return numcheck(jtxtCostprice)&&numcheck(jtxtRetailPrice)&&numcheck(jtxtQty);
    }
    private void jbtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInsertActionPerformed
    String sql = "insert into RequestGRN (Prod_Id,Prod_Name,Description,Costprice,RetailPrice,Qty,vehicleno)values(?,?,?,?,?,?,?);";   
    String Prod_Id= jtxtProductId.getText();
    String Prod_Name= jtxtProductName.getText();
    String Description= jtxtDescription.getText();
    String Costprice= jtxtCostprice.getText();
    String RetailPrice= jtxtRetailPrice.getText();
    String Qty= jtxtQty.getText();
    String vehicleno= jtxtVehicleNo.getText();
    if(!Prod_Id.equals("")&&!Prod_Name.equals("")&&!Description.equals("")&&!Costprice.equals("")&&
            !RetailPrice.equals("")&&!Qty.equals("")&&!vehicleno.equals("")){
         if(allNumCheck()){
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, Prod_Id);
            pst.setString(2, Prod_Name);
            pst.setString(3, Description);
            pst.setString(4, Costprice);
            pst.setString(5, RetailPrice);
            pst.setString(6, Qty);
            pst.setString(7, vehicleno);
            int count = pst.executeUpdate();
            if(count>0){
                JOptionPane.showMessageDialog(this, "Updated SuccessFully");
                autoId();
                jtxtProductId.setText("");
                jtxtProductName.setText("");
                jtxtDescription.setText("");
                jtxtCostprice.setText("");
                jtxtRetailPrice.setText("");
                jtxtQty.setText("");
                jtxtVehicleNo.setText("");
                jtxtProductId.requestFocus();
            }else{
             JOptionPane.showMessageDialog(this, "something went wrong");   
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(InsertProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
         }   else{
       JOptionPane.showMessageDialog(this, "please enter numbers given below"
               + "\n Costprice"
               + "\n RetailPrice"
               + "\n Qty");
       jtxtCostprice.requestFocus();
    }
    }else{
        JOptionPane.showMessageDialog(this, "Please fill everything");
    }
    
    }//GEN-LAST:event_jbtnInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTrackId;
    private javax.swing.JLabel jUserId;
    private javax.swing.JLabel jUserName;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnInsert;
    private javax.swing.JTextField jtxtCostprice;
    private javax.swing.JTextField jtxtDescription;
    private javax.swing.JTextField jtxtProductId;
    private javax.swing.JTextField jtxtProductName;
    private javax.swing.JTextField jtxtQty;
    private javax.swing.JLabel jtxtQuality;
    private javax.swing.JTextField jtxtRetailPrice;
    private javax.swing.JTextField jtxtVehicleNo;
    // End of variables declaration//GEN-END:variables
}
