package Process;


import Log.Login;
import Users.Billing;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 91979
 */
public class InvoiceAndSendMaterial extends javax.swing.JFrame {
    private Connection con;
    private static PreparedStatement pst;
    private static ResultSet rs;
    private String name;
    private String userType;
    private int id;
    private static String Order_Qty;
    private static String db_Qty;
    
    private String S_no;
    private String Order_num; 
    private String Prod_id;
    private String Prod_Name;
    private String Description;
    private String Price;
    private String Qty;
    private String Status; 
    /**
     * Creates new form Admin
     */
    public InvoiceAndSendMaterial() {
        initComponents();
        this.con = Login.connection();
        }
    
    public InvoiceAndSendMaterial(String name, int id,String userType,Connection con,String S_no,String Order_num,String Prod_id,String Prod_Name,String Description,String Price, String Qty,String Status) {
       initComponents();
       this.S_no = S_no;
       this.Order_num = Order_num;
       this.Prod_id = Prod_id;
       this.Prod_Name = Prod_Name;
       this.Description = Description;
       this.Price = Price;
       this.Qty = Qty;
       this.Status = Status;
       this.con= con;
       this.name = name;
       this.userType = userType;
       this.id=id;
       jUserId.setText(String.valueOf(id));
       jUserName.setText(name);
       autoId();
       setUpFileds();
       jtxtVhcl.requestFocus();
       }
   
    
    private void setUpFileds(){
        jOrderNo.setText(Order_num);
        jtxtProducId.setText(Prod_id);
        jProdName.setText(Prod_Name);        
        jPrice.setText(Price);        
        jStatus.setText(Status);        
        jtxtQty.setText(Qty);        
        jDescription.setText(Description);
        int TotalCost = Integer.parseInt(Qty) * Integer.parseInt(Price);
        jtxtTotalCost.setText(String.valueOf(TotalCost));
        jOrderNo.setEditable(false);
        jtxtProducId.setEditable(false);
        jProdName.setEditable(false);
        jPrice.setEditable(false);
        jStatus.setEditable(false);
        jtxtQty.setEditable(false);
        jDescription.setEditable(false);
        jtxtTotalCost.setEditable(false);
    }
   private  void autoId(){
        try {
            Statement st = con.createStatement();
            String sql = "select Max(Invoice_num) max from TransferMaterialRetailer";
             rs = st.executeQuery(sql);
             rs.next();            
             rs.getString("max");
             if(rs.getString("max")==null){
                 jInvoidNo.setText("IN001");
             }else{
                 long id = Long.parseLong(rs.getString("max").substring(2, rs.getString("max").length()));
                 id++;
                 jInvoidNo.setText("IN"+String.format("%03d", id));
             }
             
        } catch (SQLException ex) {
            Logger.getLogger(InvoiceAndSendMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jUserId = new javax.swing.JLabel();
        jUserName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jInvoidNo = new javax.swing.JLabel();
        jOrderNo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtxtQty = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jbtnRequest = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jbtnClear = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jtxtProducId = new javax.swing.JTextField();
        jPrice = new javax.swing.JTextField();
        jStatus = new javax.swing.JTextField();
        jProdName = new javax.swing.JTextField();
        jDescription = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtxtVhcl = new javax.swing.JTextField();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jtxtTotalCost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Retailers Requerment Request Page");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("User Id");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Name");

        jUserId.setBackground(new java.awt.Color(255, 204, 204));
        jUserId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jUserId.setForeground(new java.awt.Color(153, 153, 255));
        jUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUserId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jUserId.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jUserName.setBackground(new java.awt.Color(255, 204, 204));
        jUserName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jUserName.setForeground(new java.awt.Color(153, 153, 255));
        jUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUserName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jUserName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setText("Product Id");

        jButton6.setBackground(new java.awt.Color(153, 204, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 255));
        jLabel14.setText("Product Name");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 255));
        jLabel15.setText("Price");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 255));
        jLabel16.setText("Order Num");

        jInvoidNo.setBackground(new java.awt.Color(102, 255, 204));
        jInvoidNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jInvoidNo.setForeground(new java.awt.Color(0, 0, 255));
        jInvoidNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInvoidNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jOrderNo.setBackground(new java.awt.Color(102, 255, 204));
        jOrderNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jOrderNo.setForeground(new java.awt.Color(0, 0, 255));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 255));
        jLabel17.setText("Qty");

        jtxtQty.setBackground(new java.awt.Color(102, 255, 204));
        jtxtQty.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtQty.setForeground(new java.awt.Color(0, 0, 255));
        jtxtQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtQtyFocusLost(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 255));
        jLabel18.setText("Status");

        jbtnRequest.setBackground(new java.awt.Color(153, 204, 255));
        jbtnRequest.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnRequest.setForeground(new java.awt.Color(0, 0, 255));
        jbtnRequest.setText("Invoice & Send");
        jbtnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRequestActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 255));
        jLabel19.setText("Description");

        jbtnClear.setBackground(new java.awt.Color(153, 204, 255));
        jbtnClear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnClear.setForeground(new java.awt.Color(0, 0, 255));
        jbtnClear.setText("Clear");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 255));
        jLabel20.setText("Invoice No");

        jtxtProducId.setBackground(new java.awt.Color(102, 255, 204));
        jtxtProducId.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtProducId.setForeground(new java.awt.Color(0, 0, 255));

        jPrice.setBackground(new java.awt.Color(102, 255, 204));
        jPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPrice.setForeground(new java.awt.Color(0, 0, 255));
        jPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPriceFocusLost(evt);
            }
        });

        jStatus.setBackground(new java.awt.Color(102, 255, 204));
        jStatus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jStatus.setForeground(new java.awt.Color(0, 0, 255));
        jStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jStatusFocusLost(evt);
            }
        });

        jProdName.setBackground(new java.awt.Color(102, 255, 204));
        jProdName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jProdName.setForeground(new java.awt.Color(0, 0, 255));

        jDescription.setBackground(new java.awt.Color(102, 255, 204));
        jDescription.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jDescription.setForeground(new java.awt.Color(0, 0, 255));
        jDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDescriptionFocusLost(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 255));
        jLabel21.setText("Vehicle No");

        jtxtVhcl.setBackground(new java.awt.Color(102, 255, 204));
        jtxtVhcl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtVhcl.setForeground(new java.awt.Color(0, 0, 255));

        txtdate.setBackground(new java.awt.Color(102, 255, 204));
        txtdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtdate.setForeground(new java.awt.Color(51, 51, 255));
        txtdate.setToolTipText("");
        txtdate.setAlignmentX(10.0F);
        txtdate.setAlignmentY(10.0F);
        txtdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdateFocusLost(evt);
            }
        });
        txtdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdateKeyPressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 255));
        jLabel22.setText("Date");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 255));
        jLabel23.setText("Total Cost");

        jtxtTotalCost.setBackground(new java.awt.Color(102, 255, 204));
        jtxtTotalCost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtTotalCost.setForeground(new java.awt.Color(0, 0, 255));
        jtxtTotalCost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtTotalCostFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jInvoidNo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addComponent(jLabel21)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtxtProducId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(33, 33, 33)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtxtVhcl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtxtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel23))
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnRequest)
                                .addGap(101, 101, 101)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel22)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInvoidNo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(jOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtProducId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jtxtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jtxtVhcl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRequest)
                    .addComponent(jbtnClear))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.gc();
        this.setVisible(false);
        new Billing(name,id,userType,con).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jbtnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRequestActionPerformed
        if(!jtxtVhcl.getText().equals("")||txtdate.getDate().equals("")){
            if(jtxtVhcl.getText().equals("")||!txtdate.getDate().equals("")){
                if(!jtxtVhcl.getText().equals("")&&!txtdate.getDate().equals("")){
                methodForSending();
                autoId();
                jtxtVhcl.setText("");
                }else{
                   JOptionPane.showMessageDialog(this, "Please Select the date and fill Vehicle Number"); 
                   jtxtVhcl.requestFocus();
                }
            }else{
               JOptionPane.showMessageDialog(this, "Please fill the Vehicle Number");
                jtxtVhcl.requestFocus();
            }
        }else{
                JOptionPane.showMessageDialog(this, "Please Select the date");
                txtdate.requestFocus();
        }
    }//GEN-LAST:event_jbtnRequestActionPerformed
    private void methodForSending(){
        String sql = "Insert into TransferMaterialRetailer(Invoice_num,Order_num,Prod_id,Prod_Name,Description,Price,Qty,Status,Vehicle,InvoiceDate,Total_cost)values (?,?,?,?,?,?,?,?,?,?,?)";
         try {
            SimpleDateFormat dateFormate = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormate.format(txtdate.getDate());
            pst = con.prepareStatement(sql);
            pst.setString(1, jInvoidNo.getText());
            pst.setString(2, Order_num);
            pst.setString(3, Prod_id);
            pst.setString(4, Prod_Name);
            pst.setString(5, Description);
            pst.setString(6, Price);
            pst.setString(7, Qty);
            pst.setString(8, "Material sended");
            pst.setString(9, jtxtVhcl.getText());
            pst.setString(10, date);
            pst.setString(11, jtxtTotalCost.getText());
            int count = pst.executeUpdate();
            if(0<count){
               sql = "Update RequermentRequest set Status = ? where Prod_id= ? and Order_num = ?";
               pst = con.prepareStatement(sql); 
               pst.setString(1, "Material sended");
               pst.setString(2, Prod_id);
               pst.setString(3, Order_num);
               count=0;
               count = pst.executeUpdate();
               if(0<count){
              sql = "Select Qty,Order_Qty from StoreTable where Prod_id =? and Prod_Name =? ";  
              pst = con.prepareStatement(sql); 
              pst.setString(1, Prod_id);
              pst.setString(2, Prod_Name);
              rs = pst.executeQuery();
              boolean check = rs.next();
              if(check){
                  String dbQty = rs.getString("Qty");
                  String Order_qty = rs.getString("Order_Qty");
                  int dqty = Integer.parseInt(dbQty)-Integer.parseInt(Qty);
                  int orqty = Integer.parseInt(Order_qty)-Integer.parseInt(Qty);
                  if(dbQty.equals(jtxtQty.getText())){
                      sql = "delete from StoreTable where Prod_id= ?";  
                        pst = con.prepareStatement(sql);
                        pst.setString(1, Prod_id);
                        count = 0;
                        count = pst.executeUpdate();
                        if(0<count){
                        JOptionPane.showMessageDialog(this, "Material Transfered Successfully.");
//                        callDeleteProcess(Order_num);
                        System.gc();
                        this.setVisible(false);
                        new Billing(name,id,userType,con).setVisible(true);
                        }else{
                        JOptionPane.showMessageDialog(this, "something went wrong while delete.");
                        }
                  }else{
                        sql = "Update StoreTable set Qty=?,Order_Qty=? where Prod_id= ?";  
                        pst = con.prepareStatement(sql);
                        pst.setString(1, String.valueOf(dqty));
                        pst.setString(2, String.valueOf(orqty));
                        pst.setString(3, Prod_id);
                        count = 0;
                        count = pst.executeUpdate();
                        if(0<count){
                        JOptionPane.showMessageDialog(this, "Material Transfered Successfully.");
                        System.gc();
                        this.setVisible(false);
                        new Billing(name,id,userType,con).setVisible(true);
                        }else{
                            JOptionPane.showMessageDialog(this, "something went wrong while Updating.");
                        }
                  }
              }else{
                 JOptionPane.showMessageDialog(this, "Something went Wrong in StoreTable Getting QTY");   
              }
               }else{
                JOptionPane.showMessageDialog(this, "Something went Wrong\nwhile Transfer Update in RequermentRequest ");   
               }
            }else{
               JOptionPane.showMessageDialog(this, "Something went Wrong");  
            }
            } catch (SQLException ex) {
                Logger.getLogger(InvoiceAndSendMaterial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
       autoId();
       jtxtVhcl.setText("");
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jtxtQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtQtyFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQtyFocusLost

    private void jPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPriceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPriceFocusLost

    private void jStatusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jStatusFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jStatusFocusLost

    private void jDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDescriptionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jDescriptionFocusLost

    private void txtdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdateKeyPressed
    }//GEN-LAST:event_txtdateKeyPressed

    private void jtxtTotalCostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtTotalCostFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalCostFocusLost

    private void txtdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdateFocusLost
      
    }//GEN-LAST:event_txtdateFocusLost
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceAndSendMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceAndSendMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceAndSendMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceAndSendMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceAndSendMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField jDescription;
    private javax.swing.JLabel jInvoidNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jOrderNo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPrice;
    private javax.swing.JTextField jProdName;
    private javax.swing.JTextField jStatus;
    private javax.swing.JLabel jUserId;
    private javax.swing.JLabel jUserName;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnRequest;
    private javax.swing.JTextField jtxtProducId;
    private javax.swing.JTextField jtxtQty;
    private javax.swing.JTextField jtxtTotalCost;
    private javax.swing.JTextField jtxtVhcl;
    private com.toedter.calendar.JDateChooser txtdate;
    // End of variables declaration//GEN-END:variables
}
